blockchainEHR/base/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('login/', views.loginPage, name='login'),
    path('signup/', views.signup, name='signup'),
    path('user_home/', views.user_home, name='user_home'),
    path('user_profile/', views.user_profile, name='user_profile'),

]

blockchainEHR/blockchainEHR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
]

blockchainEHR/base/models.py
from django.db import models

# Create your models here.

blockchainEHR/base/views.py
from django.shortcuts import render

# Create your views here.

def landing_page(request):
    return render(request, 'base/landing_page.html')

def loginPage(request):
    return render(request, 'base/login_index.html')

def signup(request):
    return render(request, 'base/login_signup.html')

def user_home(request):
    return render(request, 'base/user_index.html')

def user_profile(request):
    return render(request, 'base/user_profile.html')

blockchainEHR/base/templates/base/landing_page.html
<!-- Start Landing Page -->
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EHR</title>
    <link rel="stylesheet" href="{% static 'styles/landing_style.css' %}">
</head>

<body>

    <div class="landing-page">
        <header>
            <div class="container">
                <a href="#" class="logo"><b>EHR</b></a>
                <ul class="links">
                    <li>Home</li>
                    <li>About Us</li>
                    <li><a href="{% url 'base:login'%}">Login</a></li>
                </ul>
            </div>
        </header>
        <div class="content">
            <div class="container">
                <div class="info">
                    <h1>We are here for your help !!</h1>
                    <p>At EHR, we believe that true wealth is health.Our comprehensive health and wellness
                        resources are designed to empower you on your journey towards a vibrant and fulfilling life.
                        Whether you're just starting or well along the path to wellness, we're here to support, educate,
                        and inspire you every step of the way.</p>

                </div>
                <div class="image">
                    <img src="{% static 'images/hospital_landing.png'%}">
                </div>
            </div>
        </div>
    </div>
</body>

</html>


<!-- End Landing Page -->

blockchainEHR/base/templates/base/login_index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Assignment - 10 ( JS - 4 )</title>
  <link rel="icon" type="image/x-icon" href="{% static 'images/fav-icon.png'%}" />
  <!-- stylesheets link -->
  <!-- font awesome -->
  <link rel="stylesheet" href="{% static 'styles/login_all.min.css' %}" />
  <!-- bootstrap -->
  <link rel="stylesheet" href="{% static 'styles/login_bootstrap.min.css' %}" />
  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
  <!-- custom stylesheets -->
  <link rel="stylesheet" href="{% static 'styles/login_style.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/login_media.css' %}" />
</head>

<body>

  <header class="login">
    <div class="container">
      <div class="login-body">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-5">
            <div class="login-form">
              <h3>SIGN IN</h3>
              <form action="">
                <div class="mail-input">
                  <div class="input-group flex-nowrap">
                    <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-envelope"></i></span>
                    <input id="signInEmail" type="email" class="form-control" placeholder="Email" aria-label="Username"
                      aria-describedby="addon-wrapping" />
                  </div>
                </div>
                <div class="password-input">
                  <div class="input-group flex-nowrap">
                    <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-lock"></i></span>
                    <input id="signInPassword" type="password" class="form-control" placeholder="Password"
                      aria-label="Username" aria-describedby="addon-wrapping" />
                  </div>
                </div>
                <p id="loginError" class="alert text-danger d-none">
                  Your email or password is wrong or cant be empty
                </p>
                <a id="signInBtn" class="submit d-block m-auto mb-5">
                  Login
                </a>
              </form>
              <a href="{% url 'base:signup' %}">Do not have an account ? Sign Up</a>
            </div>
          </div>
          <div class="col-md-5">
            <div class="login-img">
              <img src="{% static 'images/doctor.png' %}" alt="" class="img-fluid" />
            </div>
          </div>

        </div>
      </div>
    </div>
  </header>

</body>

</html>

blockchainEHR/base/templates/base/login_signup.html
{%load static%}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Login Page</title>
  <link rel="icon" type="image/x-icon" href="{% static 'images/fav-icon.png' %}" />
  <!-- stylesheets link -->
  <!-- font awesome -->
  <link rel="stylesheet" href="{% static 'styles/login_all.min.css' %}" />
  <!-- bootstrap -->
  <link rel="stylesheet" href="{% static 'styles/login_bootstrap.min.css' %}" />
  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
  <!-- custom stylesheets -->
  <link rel="stylesheet" href="{% static 'styles/login_style.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/login_media.css' %}" />
</head>

<body>
  <header class="login position-relative">
    <div class="container">
      <div class="login-body">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-5">
            <div class="login-img">
              <img src="{% static 'images/signup.png' %}" alt="" class="img-fluid" />
            </div>
          </div>
          <div class="col-md-5">
            <div class="login-form">
              <h3>SIGN UP</h3>
              <form action="">
                <div class="name-input">
                  <div class="input-group flex-nowrap has-validation">
                    <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-pen"></i></span>
                    <input id="userName" type="text" class="form-control" placeholder="Name" aria-label="Username"
                      aria-describedby="addon-wrapping" />
                  </div>
                  <div id="validationServerUsernameFeedback" class="invalid-feedback text-start ms-5 d-none">
                    <ul>
                      Please enter a valid name.
                      <li>Must be more than 1 character</li>
                      <li>Must not end with space</li>
                      <li>
                        Must not contain any number order special character
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="mail-input">
                  <div class="input-group flex-nowrap has-validation">
                    <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-envelope"></i></span>
                    <input id="userEmail" type="email" class="form-control" placeholder="Email" aria-label="Username"
                      aria-describedby="addon-wrapping" />
                  </div>
                  <div id="validationServer03Feedback" class="invalid-feedback text-start ms-5 d-none">
                    <ul>
                      Please enter a valid email.
                      <li>Must contain @</li>
                      <li>Must end with a domain EX: .com</li>
                    </ul>
                  </div>
                  <div id="validationTextarea" class="invalid-feedback text-start ms-5 d-none">
                    <ul>
                      Email used before.
                    </ul>
                  </div>
                </div>
                <div class="password-input">
                  <div class="input-group flex-nowrap has-validation">
                    <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-lock"></i></span>
                    <input id="userPassword" type="password" class="form-control" placeholder="Password"
                      aria-label="Username" aria-describedby="addon-wrapping" />
                  </div>
                  <div id="validationServer04Feedback" class="invalid-feedback text-start ms-5 d-none">
                    <ul>
                      Please enter a valid password.
                      <li>First letter must be capital</li>
                      <li>Password length Must be 8 or more</li>
                      <li>Must contain at least one number</li>
                      <li>Must not contain any spaces</li>
                    </ul>
                  </div>
                </div>
                <button id="signUpBtn" class="submit">Sign up</button>
              </form>
              <a href="{% url 'base:login' %}">You already have account ? Sign in</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="Register" class="registration d-none">
      <div class="container">
        <div class="congratulation">
          <h1>Congratulation</h1>
          <p>Your account is created successfully</p>
          <a class="log-in" href="{% url 'base:login' %}">Log in</a>
          <a class="sign-up" href="{% url 'base:signup' %}">Create another account</a>
        </div>
      </div>
    </div>
  </header>
  <!-- <script src="../js/custom.js"></script> -->
</body>

</html>

blockchainEHR/base/templates/base/navbar.html
<div class="sidebar">
    <div class="logo-details">
        <i class="bx bx-plus-medical icon"></i>
        <div class="logo_name">EHR</div>
        <i class='bx bx-menu' id="btn"></i>
    </div>
    <ul class="nav-list">

        <li>
            <a href="#">
                <i class='bx bx-grid-alt'></i>
                <span class="links_name">Dashboard</span>
            </a>
            <span class="tooltip">Dashboard</span>

        </li>
        <li>
            <a href="#">
                <i class='bx bx-user'></i>
                <span class="links_name">User</span>
            </a>
            <span class="tooltip">User</span>
        </li>
        <li>
            <a href="#">
                <i class='bx bx-pie-chart-alt-2'></i>
                <span class="links_name">Recent Visits</span>
            </a>
            <span class="tooltip">Recent visits</span>
        </li>
        <li>
            <a href="#">
                <i class='bx bx-cog'></i>
                <span class="links_name">Setting</span>
            </a>
            <span class="tooltip">Settings</span>
        </li>
        <li class="profile">
            <div class="profile-details">
                <img src="profile.jpg" alt="profileImg">
                <div class="name_job">
                    <div class="name">Prem Shahi</div>
                    <div class="job">Web designer</div>
                </div>
            </div>
            <a href="#"><i class='bx bx-log-out' id="log_out"></i></a>
        </li>
    </ul>
</div>

blockchainEHR/base/templates/base/user_index.html
{%load static%}
<!DOCTYPE html>
<!-- Created by CodingLab |www.youtube.com/CodingLabYT-->
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <title>Electronic Health Records</title>
    <link rel="stylesheet" href="{% static 'styles/user_frontend.css' %}">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha384-xxsDVmVLKA#5TiW5nRxpS07kFjOKPxX6VJ+5cW6tTI+3s27X1C5fOM+IbbqB6fWI" crossorigin="anonymous">

    <script src="{% static 'js/user_frontend.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="sidebar">
        <div class="logo-details">
            <i class="bx bx-plus-medical icon"></i>
            <div class="logo_name">EHR</div>
            <i class='bx bx-menu' id="btn"></i>
        </div>
        <ul class="nav-list">

            <li>
                <a href="#">
                    <i class='bx bx-grid-alt'></i>
                    <span class="links_name">Dashboard</span>
                </a>
                <span class="tooltip">Dashboard</span>

            </li>
            <li>
                <a href="{%url 'base:user_profile' %}">
                    <i class='bx bx-user'></i>
                    <span class="links_name">User</span>
                </a>
                <span class="tooltip">User</span>
            </li>
            <li>
                <a href="#">
                    <i class='bx bx-pie-chart-alt-2'></i>
                    <span class="links_name">Recent Visits</span>
                </a>
                <span class="tooltip">Recent visits</span>
            </li>
            <li>
                <a href="#">
                    <i class='bx bx-cog'></i>
                    <span class="links_name">Setting</span>
                </a>
                <span class="tooltip">Setting</span>
            </li>
            <li class="profile">
                <div class="profile-details">
                    <img src="{% static 'images/profile.jpg' %}" alt="profileImg">
                    <div class="name_job">
                        <div class="name">Prem Shahi</div>
                        <div class="job">Web designer</div>
                    </div>
                </div>
                <a href="#"><i class='bx bx-log-out' id="log_out"></i></a>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <div class="dashboard-container">
            <div class="text">Dashboard</div>
            <div class="current_date" id="current_date"></div>
            <div class="user_icon">
                <a href="#">user_icon</a>
            </div>
        </div>

        <div class="main-content">
            <div class="first-row">
                <div class="personal-card">
                    <div class="user-img">
                        <img src="https://codingyaar.com/wp-content/uploads/bootstrap-profile-card-image.jpg"
                            class="card-img-top" alt="...">
                        <h5>Manav Sidana</h5>
                        <p class="user-email">manavsidana50@gmail.com</p>
                    </div>
                    <div class="vertical-line">
                        <hr width="1" size="500" style=" margin:0 auto;" />
                    </div>
                    <div class="user-info">
                        <div class="user-info1">
                            <h6 class="user-gender">Gender</h6>
                            <p class="user-gender"></p>
                            <h6 class="user-phone">Phone Number</h6>
                            <p class="user-phone"></p>
                            <h6 class="user-city">City</h6>
                            <p class="user-city"></p>
                            <h6 class="user-registration-date">Registration Date</h6>
                            <p class="user-registration-date"></p>
                        </div>
                        <div class="user-info2">
                        </div>
                    </div>
                </div>
                <div class="recent-visits-card">
                    <div class="visit-header">
                        <p>Recent Visits</p>
                        <a href="#">View All</a>
                    </div>
                    <div class="visit-body">
                        doctor name
                        date
                        description
                        pres
                        status
                    </div>
                </div>
                <div class="files-card">
                    <div class="files-header">
                        <p>Files / Documents</p>
                        <a href="#">View All</a>
                    </div>
                </div>

            </div>

            <div class="second-row">
                <div class="doctors-card">

                </div>
                <div class="user-diseases-card">

                </div>
            </div>
        </div>

    </section>

</body>

</html>

blockchainEHR/base/templates/base/user_profile.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="{% static 'js/sidebar.js' %}"></script>
    <link rel="stylesheet" href="{% static 'styles/navbar.css' %}">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'styles/user_profile.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/h5.1h5.3/css/all.min.css"
        integrity="sha384-xxsDVmVLKA#h5TiWh5nRxpS07kFjOKPxX6VJ+h5cW6tTI+3s27X1Ch5fOM+IbbqB6fWI" crossorigin="anonymous">


    <title>User Profile</title>
</head>

<body>
    <div class="sidebar">
        <div class="logo-details">
            <i class="bx bx-plus-medical icon"></i>
            <div class="logo_name">EHR</div>
            <i class='bx bx-menu' id="btn"></i>
        </div>
        <ul class="nav-list">

            <li>
                <a href="#">
                    <i class='bx bx-grid-alt'></i>
                    <span class="links_name">Dashboard</span>
                </a>
                <span class="tooltip">Dashboard</span>

            </li>
            <li>
                <a href="{%url 'base:user_profile' %}">
                    <i class='bx bx-user'></i>
                    <span class="links_name">User</span>
                </a>
                <span class="tooltip">User</span>
            </li>
            <li>
                <a href="#">
                    <i class='bx bx-pie-chart-alt-2'></i>
                    <span class="links_name">Recent Visits</span>
                </a>
                <span class="tooltip">Recent visits</span>
            </li>
            <li>
                <a href="#">
                    <i class='bx bx-cog'></i>
                    <span class="links_name">Setting</span>
                </a>
                <span class="tooltip">Setting</span>
            </li>
            <li class="profile">
                <div class="profile-details">
                    <img src="{% static 'images/profile.jpg' %}" alt="profileImg">
                    <div class="name_job">
                        <div class="name">Prem Shahi</div>
                        <div class="job">Web designer</div>
                    </div>
                </div>
                <a href="#"><i class='bx bx-log-out' id="log_out"></i></a>
            </li>
        </ul>
    </div>
    <div id="nav-placeholder"></div>
    <div class="home-section">
        <div class="user-pic">
            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Maxwell Admin">
            <p class="name">Manav Sidana</p>
            <p class="email">manavsidana00@gmail.com</p>
            <p class="joined-date">Joined: 12/01/20</p>

            <button type="button" id="edit-btn">Edit details</button>
        </div>
        <div class="user-details">
            <div class="details-row-1">
                <h5>Gender</h5>
                <input type="text" name="gender" id="gender" placeholder="male">
                <h5>Birthday</h5>
                <input type="text" name="dob" id="dob" placeholder="1/2/3">
                <h5>Aadhaar No.</h5>
                <input type="text" name="aadhaar" id="aadhaar" placeholder="1231 1231 23h54 2h564">
                <h5>Phone No.</h5>
                <input type="text" name="phone-no" id="phone-no" placeholder="9988h566892">

            </div>
            <div class="details-row-2">
                <h5>Age</h5>
                <input type="text" name="age" id="age" placeholder="17">
                <h5>Address</h5>
                <input type="text" name="address" id="address" placeholder="24/1, Patiala">
                <h5>Emergency Contact</h5>
                <input type="text" name="emergency-contact" id="emergency-contact" placeholder="9988h566892">

            </div>
        </div>
    </div>

    <script>
        $(function () {
            $("#nav-placeholder").load("navbar.html");
        });
    </script>
</body>

</html>

blockchainEHR/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EHR</title>
    <link rel="stylesheet" href="{% static 'styles/landing_style.css' %}">
    <link rel="stylesheet" href="{% static 'styles/user_frontend.css' %}">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha384-xxsDVmVLKA#5TiW5nRxpS07kFjOKPxX6VJ+5cW6tTI+3s27X1C5fOM+IbbqB6fWI" crossorigin="anonymous">
    <script src="{% static 'js/login_signin.js' %}"></script>

    <script src="{% static 'js/user_frontend.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="{% static 'js/sidebar.js' %}"></script>
    <link rel="stylesheet" href="{% static 'styles/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'styles/user_profile.css' %}">
    <link rel="stylesheet" href="{% static 'styles/landing_style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/fav-icon.png' %}" />
    <link rel="stylesheet" href="{% static 'styles/login_all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/login_bootstrap.min.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'styles/login_style.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/login_media.css' %}" />
</head>

<body>
    {%include 'navbar.html' %}

    {% block content %}

    {% endblock %}
</body>

</html>

blockchainEHR/templates/navbar.html
{%load static%}

<div class="sidebar">
    <div class="logo-details">
        <i class="bx bx-plus-medical icon"></i>
        <div class="logo_name">EHR</div>
        <i class='bx bx-menu' id="btn"></i>
    </div>
    <ul class="nav-list">

        <li>
            <a href="#">
                <i class='bx bx-grid-alt'></i>
                <span class="links_name">Dashboard</span>
            </a>
            <span class="tooltip">Dashboard</span>

        </li>
        <li>
            <a href="#">
                <i class='bx bx-user'></i>
                <span class="links_name">User</span>
            </a>
            <span class="tooltip">User</span>
        </li>
        <li>
            <a href="#">
                <i class='bx bx-pie-chart-alt-2'></i>
                <span class="links_name">Recent Visits</span>
            </a>
            <span class="tooltip">Recent visits</span>
        </li>
        <li>
            <a href="#">
                <i class='bx bx-cog'></i>
                <span class="links_name">Setting</span>
            </a>
            <span class="tooltip">Settings</span>
        </li>
        <li class="profile">
            <div class="profile-details">
                <img src="{%static 'images/profile.jpg'%}" alt="profileImg">
                <div class="name_job">
                    <div class="name">Prem Shahi</div>
                    <div class="job">Web designer</div>
                </div>
            </div>
            <a href="#"><i class='bx bx-log-out' id="log_out"></i></a>
        </li>
    </ul>
</div>